# SPDX-License-Identifier: Apache-2.0
"""``render_launch_script(cfg, ...)`` — top-level bash launch emitter.

Pure function; takes a ``ModelConfig`` and returns the rendered
executable bash script as a string. Previously
``ModelConfig.to_launch_script`` in ``model_configs/schema.py``. Body
unchanged.

Output is either docker-based (when ``cfg.docker`` is set) or
bare-metal depending on the config. Either way: env vars exported,
vllm serve called with all flags.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Optional

from .docker_cmd import build_docker_cmd
from .llamacpp_cmd import build_llamacpp_cmd, build_llamacpp_docker_cmd
from .shell import shell_quote
from .vllm_cmd import build_vllm_cmd

if TYPE_CHECKING:
    from ..schema import ModelConfig


def render_launch_script(
    cfg: "ModelConfig",
    host_paths: Optional[dict[str, str]] = None,
    *,
    strict_mounts: bool = False,
) -> str:
    """Render ``cfg`` as an executable bash launch script.

    Args:
        cfg: ModelConfig to render.
        host_paths: optional mapping of symbolic mount variables to
            absolute paths. Used to resolve ``${models_dir}``,
            ``${hf_cache}`` etc. in ``docker.mounts``. If None, tries
            to load ``host.yaml`` lazily — but only if any mount
            actually contains a ``${var}`` reference. Configs with
            fully-absolute mounts work without a host config.
        strict_mounts: if True, raise SchemaError on any unresolved
            ``${var}`` reference in ``docker.mounts``. Live launch
            paths should pass True so missing host.yaml entries
            fail loudly instead of producing an unbootable script.
            Default False — ``--dry-run`` previews can leave
            placeholders for documentation purposes.

    P0-8 fix (audit 2026-05-08): ``strict_mounts`` threaded through
    so live launch ≠ dry-run preview. Previously both paths used
    strict=False and a Docker config with missing host.yaml
    rendered an unbootable script with literal ``${models_dir}``.

    F-016 fix (audit 2026-05-07): previously ``_build_docker_cmd``
    embedded mounts as-is, so configs using symbolic refs got
    ``${models_dir}`` literally in the docker cmd → boot failure.
    """
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by Genesis model_config:",
        f"#   key:           {cfg.key}",
        f"#   title:         {cfg.title}",
        f"#   maintainer:    {cfg.maintainer}",
        f"#   schema_v:      {cfg.schema_version}",
    ]
    if cfg.last_validated:
        lines.append(f"#   last_validated: {cfg.last_validated}")
    if cfg.genesis_pin:
        lines.append(f"#   genesis_pin:   {cfg.genesis_pin}")
    if cfg.vllm_pin_required:
        lines.append(f"#   vllm_pin:      {cfg.vllm_pin_required}")
    if cfg.reference_metrics:
        rm = cfg.reference_metrics
        lines.append(
            f"#   reference:     {rm.long_gen_sustained_tps:.1f} TPS "
            f"sustained / {rm.tool_call_score} tool / "
            f"CV {rm.stability_cv_pct:.2f}% / "
            f"VRAM {rm.vram_total_mib} MiB"
        )
    for note in cfg.notes:
        lines.append(f"#   note: {note}")
    lines.extend(["", "set -euo pipefail", ""])

    # System env
    if cfg.system_env:
        lines.append("# System env")
        for k, v in sorted(cfg.system_env.items()):
            lines.append(f'export {k}={shell_quote(v)}')
        lines.append("")

    # Genesis env
    if cfg.genesis_env:
        lines.append("# Genesis patcher env")
        for k, v in sorted(cfg.genesis_env.items()):
            lines.append(f'export {k}={shell_quote(v)}')
        lines.append("")

    # Multi-engine dispatch (Phase 1, 2026-06-27). The vLLM branch is
    # UNCHANGED — it fires for engine == "vllm" (the default for every
    # existing config), so vLLM presets render a byte-identical script. The
    # llama.cpp branch builds the llama-server GGUF command + a docker run
    # with the pinned llama.cpp image and NO Genesis apply step.
    if getattr(cfg, "engine", "vllm") == "llama-cpp":
        cmd_parts = build_llamacpp_cmd(cfg)
        if cfg.docker:
            lines.append("# Docker launch (llama.cpp)")
            lines.append(build_llamacpp_docker_cmd(
                cfg, cmd_parts, host_paths=host_paths,
                strict_mounts=strict_mounts,
            ))
        else:
            lines.append("# Bare-metal launch (llama.cpp)")
            lines.append("exec " + " \\\n  ".join(cmd_parts))
        return "\n".join(lines) + "\n"

    # Build vllm serve cmd
    cmd_parts = build_vllm_cmd(cfg)

    # Docker or bare-metal launch
    if cfg.docker:
        lines.append("# Docker launch")
        docker_cmd = build_docker_cmd(
            cfg, cmd_parts, host_paths=host_paths,
            strict_mounts=strict_mounts,
        )
        lines.append(docker_cmd)
    else:
        lines.append("# Bare-metal launch")
        lines.append("exec " + " \\\n  ".join(cmd_parts))

    return "\n".join(lines) + "\n"
